### ISSUE TITLE
Egl error

### ISSUE THREAD

**Issue by Passenger12138** [BrokenSource/DepthFlow#57]
### 🔘 Operating system

Linux (Ubuntu-like)

### 🔘 Runtime enviroment

PyPI Wheels (pip, poetry, pdm, rye, uv, etc)

### 🔘 Python version

Python 3.12

### 🔘 GPU Vendor

NVIDIA Desktop

### 🔘 Description

I follow the turtoil to install pypi,
```
pip install depthflow
```
 I test the all way s for debug ther egl error such as SHADERFLOW_BACKEND=headless or xvfb-run -a ,  But i always get the error 
this is my exec order 
```
export WINDOW_BACKEND=headless
depthflow input -i https://w.wallhaven.cc/full/2y/wallhaven-2y6wwg.jpg main -o ./video.mp4
```
or 
```
xvfb-run depthflow input -i https://w.wallhaven.cc/full/2y/wallhaven-2y6wwg.jpg main -o ./video.mp4
```
I get the same error
![image](https://github.com/user-attachments/assets/5e8cd9ac-c262-4c7f-a5ea-e97b18b7ac29)

**Comment by Tremeschin** [comment]
Is this running on a server as you commented on another issue?

- if it's on runpod, which had these egl initialization errors, you can follow this https://brokensrc.dev/get/docker/#runpod

- if you're running locally, ensure you have nvidia drivers and (don't know for ubuntu) nvidia-utils package with the actual graphics apis libraries

Also, avoid xvfb-run at all costs. There's an explanation why on the same link above

let me know if these work and/or your server provider (if it's not on that "tested" list) so I can help you further!

**Comment by Passenger12138** [comment]
Tank you for your advice, and I successful run depthflow in the server by dockerfile. But I notice the dockerfile use the torch-cpu run,fot render the model, I would be grateful if you can give a torch-cuda and gpu render the video dockerfile。 Or I just modify the toch-cuda could make the depth-estimater model run in the gpu and opengl renader in the gpu. I would be grateful if y could give me some advice
![image](https://github.com/user-attachments/assets/1d5b2378-2b4c-4254-94e7-49468d6b2a64)

**Comment by Tremeschin** [comment]
Awesome!

For torch cuda, can simply swap that extra index url to:

```dockerfile
RUN pip install torch==2.4.1 --index-url https://download.pytorch.org/whl/cu121
```

and/or any valid one found at https://pytorch.org/ by scrolling down a bit

I chose torch cpu just in case people try running with AMD, Intel or Apple Silicon GPUs as it obviously doesn't depend on the GPU brand and is universal :)

**Comment by Passenger12138** [comment]
Wow, wonderful 
tank you, Another question is that could you tell me how to modify the param in the infra
Now I infra the 2.5d video by 
```
WINDOW_BACKEND=headless depthflow input -i https://w.wallhaven.cc/full/2y/wallhaven-2y6wwg.jpg main -o ./video.mp4
```
I  try  set the fps=30 and the time =5 by
```
WINDOW_BACKEND=headless depthflow input -i https://w.wallhaven.cc/full/2y/wallhaven-2y6wwg.jpg main -o ./video.mp4 -r 30
```
But I get the error
![image](https://github.com/user-attachments/assets/996ea589-0c6b-42a8-bcaa-a69ea3751a65)
Your code is encapsulated so well that I can't edit it quickly such the fps and time. Could you give me some advice？

**Comment by Tremeschin** [comment]
`-r` is for `render` (implicit when setting `-o /path`), I'm using `-f` or `--fps` for the framerate!

![image](https://github.com/user-attachments/assets/4096fa26-ae13-4425-94d2-69229b6c7ceb)

So in your case, for fps=30 and time=5

```
WINDOW_BACKEND=headless depthflow input -i https://w.wallhaven.cc/full/2y/wallhaven-2y6wwg.jpg main -o ./video.mp4 -f 30 -t 5
```

**Comment by Tremeschin** [comment]
Forgot to mention that all these parameters are shared between the `main` cli command and the `main` method itself:

https://github.com/BrokenSource/DepthFlow/blob/c500cc8251577896e938ddd60780ba0602bb16f1/Examples/Custom.py#L34-L41

**Comment by Passenger12138** [comment]
great work. I love it

**Comment by Passenger12138** [comment]
Sorry to bother you again, I would like to guide you on how to quickly specify different depth prediction models 
I try 
```
WINDOW_BACKEND=headless depthflow  input -i https://w.wallhaven.cc/full/2y/wallhaven-2y6wwg.jpg depthpro  main   -o ./video.mp4
```
But I meet error 
![image](https://github.com/user-attachments/assets/3631d84d-d56f-4dcf-929f-366d90bdbf71)
I check the help get 
![image](https://github.com/user-attachments/assets/f0244d0c-7610-4aa4-9ba8-f42a76bc01fd)
Could you tell me how to use other depth estimatorand ohetr param not motion in the doc in https://brokensrc.dev/depthflow/quick/examples/?

**Comment by Tremeschin** [comment]
maybe the system is missing `git` as apple didn't provide a pypi package of depth-pro, and it's doing a `pip install git+https://github.com/apple/ml-depth-pro`, try running `apt update && apt install git` on your base image as well

**Comment by killy001** [comment]
`│DepthFlow├┤1'01.612├┤INFO   │ ▸ (Module  1 • CustomDepthf) Initializing scene 'CustomDepthflowScene' with backend headless
!!! Exception during processing !!! requested device index 0, but found 0 devices
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 293, in apply_depthflow
    scene = CustomDepthflowScene(
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 59, in __init__
    DepthScene.__init__(self, **kwargs)
  File "<attrs generated init DepthFlow.Scene.DepthScene>", line 101, in __init__
    self.__attrs_post_init__()
  File "/opt/conda/lib/python3.10/site-packages/Broken/Core/__init__.py", line 504, in __attrs_post_init__
    method(self)
  File "/opt/conda/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 120, in __post__
    self._build()
  File "/opt/conda/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 138, in _build
    self.init_window()
  File "/opt/conda/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 495, in init_window
    self.window = importlib.import_module(module).Window(
  File "/opt/conda/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 25, in __init__
    self.init_mgl_context()
  File "/opt/conda/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 36, in init_mgl_context
    self._ctx = moderngl.create_standalone_context(
  File "/opt/conda/lib/python3.10/site-packages/moderngl/__init__.py", line 2304, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/moderngl/__init__.py", line 2254, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/opt/conda/lib/python3.10/site-packages/glcontext/__init__.py", line 120, in create
    return egl.create_context(**kwargs)
Exception: requested device index 0, but found 0 devices`

GPU显卡是有的，型号A10，请问这个错误怎么解决呢

**Comment by Tremeschin** [comment]
<div align="justify">

@killy001 Take a look at the [nvidia section](https://github.com/BrokenSource/BrokenSource/blob/main/Docker/broken-base.dockerfile#L22) of my dockerfiles that I'm setting up dependencies and opengl loaders!

Your environment seems to be missing even basic mesa dependencies for CPU rendering to fallback and take place with `llvmpipe` for EGL (most notably the packages `libglvnd0 libglvnd-dev libegl1-mesa-dev` for ubuntu 24.04, and `libglvnd0 libglvnd-dev libegl1-mesa` for ubuntu 22.04)

If you're running in a container, make sure to have the [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) installed on the **host** (if it's a cloud provider, most likely they have it, but some disable `graphics,gpu` capabilities, that would _work_ but not find the GPU and use CPU rendering, perfomrance will be terrible)

I have a lengthy write-up here https://brokensrc.dev/get/docker/ for docker and cloud (I need to simplify a bit 😅)

**Comment by killy001** [comment]
```
2024-12-25T07:16:12.116290 - Prompt executed in 2.25 seconds
2024-12-25T07:17:24.201205 - got prompt
2024-12-25T07:17:24.254405 - │DepthFlow├┤1'22.937├┤INFO   │ ▸ (Module  2 • CustomDepthf) Initializing scene 'CustomDepthflowScene' with backend headless
2024-12-25T07:17:24.264139 - !!! Exception during processing !!! eglGetPlatformDisplayEXT failed (0x3000)
2024-12-25T07:17:24.264436 - Traceback (most recent call last):
  File "/app/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/app/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/app/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 293, in apply_depthflow
    scene = CustomDepthflowScene(
  File "/app/ComfyUI/custom_nodes/ComfyUI-Depthflow-Nodes/src/depthflow.py", line 59, in __init__
    DepthScene.__init__(self, **kwargs)
  File "<attrs generated init DepthFlow.Scene.DepthScene>", line 101, in __init__
    self.__attrs_post_init__()
  File "/usr/local/python3/lib/python3.10/site-packages/Broken/Core/__init__.py", line 504, in __attrs_post_init__
    method(self)
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 120, in __post__
    self._build()
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 138, in _build
    self.init_window()
  File "/usr/local/python3/lib/python3.10/site-packages/ShaderFlow/Scene.py", line 495, in init_window
    self.window = importlib.import_module(module).Window(
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 25, in __init__
    self.init_mgl_context()
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl_window/context/headless/window.py", line 36, in init_mgl_context
    self._ctx = moderngl.create_standalone_context(
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl/__init__.py", line 2304, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/moderngl/__init__.py", line 2254, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/usr/local/python3/lib/python3.10/site-packages/glcontext/__init__.py", line 120, in create
    return egl.create_context(**kwargs)
Exception: eglGetPlatformDisplayEXT failed (0x3000)
```

Enviroment:

Linux Centos7
Python 3.10
Nvidia A10

Could you give me some advice？
